target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'chess', :path => '../chess'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
  end
 end
end
