target 'iosApp' do
  use_frameworks!
  platform :ios, '15'
#  pod 'chess', :path => '../chess'
#  pod 'bluetoothchat', :path => '../bluetoothchat'
  pod 'sharedmodels', :path => '../sharedmodels'
  pod 'Firebase/Analytics'
end
